steps:
  # Read variables from CLI
  - read: project_name
    prompt: What is the project name?
    default: a_project_name
  - read: company_name
    prompt: What is the company name?
    default: a_company_name

  # Write to user_variables template file
  - update:
      path: "./src/user_variables.template.ts"
