steps:
  # Read variables from CLI
  - read: project_name
    prompt: What is the project name?
  - read: company_name
    prompt: What is the company name?

  # Write to user_variables file
  # - update: "./user_variables.template.ts"
  - update: test.md
